### ISSUE TITLE
Work all browser ?

### ISSUE THREAD

**Issue by leoproject** [jprochazk/cbor#1]
Hi dude,
Firstly congratulations on your project. I am using your library in ionic apps. In android that´s ok. However, iOS isn't working.
Have you any problem with the Safari browser?

**Comment by jprochazk** [comment]
Thank you for using the library!

I have not tested the library on safari. I tried to make sure not to use features which aren't available on all major browsers. Do you have any stack traces or errors I could take a look at?

**Comment by leoproject** [comment]
So guy, the app in Ionic didn't report any problem with this. When  I want to go the page with code that has your library, not work, but  I comment on this part that has CBOR.decode, works.

I am researching a way that to appear the error about this. What's strange that on Android works perfectly, but iOS does not.

**Comment by jprochazk** [comment]
Could you share the data that is being encoded/decoded?

**Comment by leoproject** [comment]
I apologize for the delayed answer. The question was of the decoding in Safari. As I as had a time-limited.  I used the code from the CBOR-JS library (https://github.com/paroga/cbor-js).

 But thanks by help man! Again congratulations on work!
